version: "3"

services:
  webserver1:
    build: 
      context: ./.docker/bin/webserver
    container_name: 'png-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        - postgres
    volumes:
      - ${DOCUMENT_ROOT-./public}:/var/www/public
      - ${PHP_INI-./.docker/config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./.docker/config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./.docker/logs/apache2}:/var/log/apache2
      - .:/var/www
    working_dir: /var/www

  postgres:
    image: postgres
    restart: always
    container_name: 'png-postgres'
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: bank
      POSTGRES_DB: bank
    volumes:
        - ${POSTGRES_DATA_DIR-./.docker/data/postgres}:/var/lib/postgresql/data
    ports:
      - "5432:5432"